### PR TITLE
Catch up with Embulk v0.10.19

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Review by minidragon88 — COMMENTED** [review]
Just see the usage of:
* Exec.getBufferAllocator()
* Exec.newTaskReport()
* Exec.newConfigDiff()
in https://github.com/embulk/embulk-input-ftp/blob/catch-up-with-v0.10/embulk-input-ftp/src/main/java/org/embulk/input/FtpFileInputPlugin.java

Should we change them? @dmikurube

**Comment by dmikurube** [comment]
@minidragon88 Ah, thanks for the good catch.

`Exec.newConfigDiff` and `Exec.newTaskReport` are (not in a hurry, but finally) to be replaced to `CONFIG_MAPPER_FACTORY.new...`. Done it in 0f1d5a5348a772fd4a996a8e5f5e671cdc98c2db.

`Exec.getBufferAllocator` is an expected use.

**Review by minidragon88 — APPROVED** [review]
LGTM

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
